name = "r2-upload"
main = "cloudflare-r2-worker.js"
compatibility_date = "2026-04-01"

[[r2_buckets]]
binding = "R2BUCKET"
bucket_name = "files"

[[r2_buckets]]
binding = "CHATBUCKET"
bucket_name = "chat"
